export interface ICharacter {
    id: number,
    name: string,
    russian: string,
    image: IImage,
    url: string,
    altname: string,
    japanese: string,
    description: string,
    description_html: string,
    description_source: string,
    favoured: boolean,
    thread_id: number,
    topic_id: number,
    updated_at: string,
    seyu: ISeyu[],
    animes: IAnime[],
    mangas: IManga[]
}
interface IImage {
    original: string,
    preview: string,
    x96: string,
    x48: string,
}
interface ISeyu {
    id: number,
    name: string,
    russian: string,
    image: IImage,
    url: string,
}
interface IAnime {
    id: number,
    name: string,
    russian: string,
    image: IImage,
    url: string,
    kind: string,
    score: string,
    status: string,
    episodes: number,
    episodes_aired: number,
    aired_on: string,
    released_on: string,
    roles: [],
    role: string,
}
interface IManga {
    id: number,
    name: string,
    russian: string,
    image: IImage,
    url: string,
    kind: string,
    score: string,
    status: string,
    volumes: number,
    chapters: number,
    aired_on: string,
    released_on: string,
    roles: [],
    role: string,
}